import { randomUUID } from "node:crypto";
import { join } from "node:path";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import {
  enterpriseCredentialId,
  isAllowedLicenseEndpoint,
  verifyLicense,
} from "../core/license.js";
import {
  claimEnterpriseHostIdentity,
  inspectEnterpriseHostIdentity,
} from "../core/enterprise-host-identity.js";
import { prepareEnterpriseCredentialRotation } from "../core/enterprise-rotation.js";

/**
 * One-liner enterprise onboarding.
 *
 *   $ printenv CORTEX_API_KEY | cortex enterprise install --api-key-stdin
 *
 * Replaces the manual `.context/enterprise.yml` editing flow that's been
 * the friction point for new users. Validates the key against the
 * license endpoint before writing config — so a typo'd key fails fast
 * with a clear error rather than going silently into community-mode.
 */

const DEFAULT_ENDPOINT = "https://cortex-web-rho.vercel.app";

export type EnterpriseSetupOptions = {
  apiKey: string;
  endpoint?: string;
  cwd?: string;
};

export type EnterpriseSetupResult = {
  ok: boolean;
  message: string;
  configPath?: string;
  edition?: string;
  expiresAt?: string;
};

const API_KEY_RE = /^(?:ctx|ent)_[A-Za-z0-9._-]{8,}$/;

function buildEnterpriseYaml(baseUrl: string, apiKey: string): string {
  const lines = [
    "# Cortex enterprise configuration. Generated by `cortex enterprise install --api-key-stdin`.",
    "# Single api_key is used for telemetry, policy, audit and govern services.",
    "enterprise:",
    `  api_key: ${apiKey}`,
    `  base_url: ${baseUrl}`,
    "",
    "telemetry:",
    "  enabled: true",
    "  interval_minutes: 1",
    "",
    "compliance:",
    "  frameworks: [iso27001, iso42001, soc2]",
    "  eu_addons: false",
    "",
    "govern:",
    "  mode: off",
    "  sync_on_startup: true",
    "  sync_interval_minutes: 60",
    "  tier_claude: prevent",
    "  tier_codex: prevent",
    "  tier_copilot: wrap",
    "  detect_ungoverned: true",
    "",
  ];
  return lines.join("\n");
}

export async function runEnterpriseSetup(
  options: EnterpriseSetupOptions,
): Promise<EnterpriseSetupResult> {
  const cwd = options.cwd ?? process.cwd();
  const endpoint = (options.endpoint ?? DEFAULT_ENDPOINT).replace(/\/$/, "");
  const apiKey = options.apiKey.trim();

  if (!API_KEY_RE.test(apiKey)) {
    return {
      ok: false,
      message:
        "API key must start with 'ctx_' or 'ent_' followed by at least 8 alphanumeric/._- chars.",
    };
  }

  if (!isAllowedLicenseEndpoint(endpoint)) {
    return {
      ok: false,
      message:
        "Endpoint must use HTTPS. Plain HTTP is allowed only for localhost loopback development.",
    };
  }

  const contextDir = join(cwd, ".context");
  if (!existsSync(contextDir)) {
    return {
      ok: false,
      message: `No .context/ at ${cwd}. Run 'cortex init --bootstrap' first.`,
    };
  }

  // Validate key BEFORE writing config — fail fast, no half-configured state.
  const license = await verifyLicense(contextDir, endpoint, apiKey, {
    client_version: process.env.CORTEX_VERSION,
  });

  if (!license.valid) {
    return {
      ok: false,
      message: `License rejected: ${license.reason} (source=${license.source}). Verify the API key and endpoint are correct.`,
    };
  }
  // Write enterprise.yml.
  const configPath = join(contextDir, "enterprise.yml");
  const temporaryConfigPath = join(
    contextDir,
    `.enterprise.yml.${process.pid}.${randomUUID()}.tmp`,
  );
  try {
    mkdirSync(contextDir, { recursive: true });
    writeFileSync(
      temporaryConfigPath,
      buildEnterpriseYaml(endpoint, apiKey),
      {
        encoding: "utf8",
        mode: 0o600,
        flag: "wx",
      },
    );
    chmodSync(temporaryConfigPath, 0o600);
    renameSync(temporaryConfigPath, configPath);
    // Preserve restrictive permissions even when replacing an existing file.
    chmodSync(configPath, 0o600);
  } catch (err) {
    try {
      unlinkSync(temporaryConfigPath);
    } catch {
      // The rename may already have completed, or the temp file was not made.
    }
    return {
      ok: false,
      message: `Failed to write ${configPath}: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  return {
    ok: true,
    message: "Enterprise configuration written.",
    configPath,
    edition: license.edition,
    expiresAt: license.expires_at,
  };
}

export function bindEnterpriseIdentity(options: {
  apiKey: string;
  endpoint?: string;
  homeDir?: string;
  owner?: { uid: number; gid: number };
}): boolean {
  const endpoint = (options.endpoint ?? DEFAULT_ENDPOINT).replace(/\/$/, "");
  const apiKey = options.apiKey.trim();
  if (!API_KEY_RE.test(apiKey) || !isAllowedLicenseEndpoint(endpoint)) {
    return false;
  }
  const credentialId = enterpriseCredentialId(endpoint, apiKey);
  const identityStatus = inspectEnterpriseHostIdentity(
    credentialId,
    endpoint,
    { homeDir: options.homeDir, owner: options.owner },
  );
  if (identityStatus === "conflict" || identityStatus === "invalid") {
    return false;
  }
  if (
    identityStatus === "rotation" &&
    !prepareEnterpriseCredentialRotation(options.homeDir)
  ) {
    return false;
  }
  return claimEnterpriseHostIdentity(
    credentialId,
    endpoint,
    {
      homeDir: options.homeDir,
      owner: options.owner,
    },
  );
}
